# Generated by Django 5.1.7 on 2025-11-19 12:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('container_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('container_product', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Saraf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sarafs', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Saraf',
                'verbose_name_plural': 'Sarafs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContainerTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantity of product involved in this transaction', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('port_of_origin', models.CharField(blank=True, max_length=255)),
                ('port_of_discharge', models.CharField(blank=True, max_length=255)),
                ('total_price', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_status', models.CharField(choices=[('in_store', 'In Store'), ('sold_to_company', 'Sold to Company'), ('sold_to_customer', 'Sold to Customer')], default='in_store', max_length=32)),
                ('transport_status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('in_stock', 'In Stock')], default='pending', max_length=32)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('arrived_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_transactions', to='accounts.company')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='containers.container')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Container Transaction',
                'verbose_name_plural': 'Container Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transport_status'], name='containers__transpo_f98a2a_idx'), models.Index(fields=['arrival_date'], name='containers__arrival_9e847a_idx'), models.Index(fields=['arrived_date'], name='containers__arrived_f1c2e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inventory_List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('product_name', models.CharField(max_length=255)),
                ('make', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('in_stock_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_sold_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('total_sold_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='containers.container')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'indexes': [models.Index(fields=['code'], name='containers__code_5f60cc_idx'), models.Index(fields=['product_name'], name='containers__product_15c25e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SarafTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_from_saraf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('paid_by_company', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('debit_company', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('aed', 'AED')], db_index=True, default='usd', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('transaction_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Saraf_transactions', to='containers.container')),
                ('saraf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='containers.saraf')),
            ],
            options={
                'verbose_name': 'Saraf Transaction',
                'verbose_name_plural': 'Saraf Transactions',
                'ordering': ['-transaction_time', '-created_at'],
                'indexes': [models.Index(fields=['saraf', 'transaction_time'], name='containers__saraf_i_e1d8f3_idx'), models.Index(fields=['saraf', 'currency'], name='containers__saraf_i_101c3e_idx')],
            },
        ),
    ]
