# Generated by Django 5.1.7 on 2025-11-20 13:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_list',
            name='in_stock_qty',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventory_list',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventory_list',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='inventory_list',
            name='total_sold_qty',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventory_list',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='saraftransaction',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='saraftransaction',
            name='debit_company',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='saraftransaction',
            name='paid_by_company',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='saraftransaction',
            name='received_from_saraf',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
    ]
