# Generated by Django 5.1.7 on 2025-11-19 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='accounts.company'),
        ),
    ]
