# Generated by Django 5.1.7 on 2025-10-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='number',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='description',
            new_name='note',
        ),
        migrations.AddField(
            model_name='container',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='container',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer'),
        ),
        migrations.AddField(
            model_name='container',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
