# Generated by Django 5.1.7 on 2025-11-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_alter_inventory_list_in_stock_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saraftransaction',
            name='debit_company',
        ),
    ]
