# Generated by Django 5.1.7 on 2025-11-24 11:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_remove_saraftransaction_debit_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='saraftransaction',
            name='debit_company',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
    ]
