# Generated by Django 5.1.7 on 2025-11-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_saraftransaction_debit_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saraftransaction',
            name='debit_company',
        ),
    ]
