# Generated by Django 5.1.7 on 2025-10-06 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('container_no', models.CharField(blank=True, max_length=50)),
                ('exchange_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.exchangeoffice')),
            ],
        ),
    ]
