# Generated by Django 5.1.7 on 2025-11-29 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی هزینه',
                'verbose_name_plural': 'دسته\u200cبندی هزینه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('paid_to', models.CharField(blank=True, max_length=200, verbose_name='پرداخت به')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensecategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'هزینه روزانه',
                'verbose_name_plural': 'هزینه\u200cهای روزانه',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام آیتم')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قیمت واحد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensecategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'آیتم هزینه',
                'verbose_name_plural': 'آیتم\u200cهای هزینه',
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت واحد')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ کل')),
                ('paid_by', models.CharField(max_length=100, verbose_name='پرداخت کننده')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('bank', 'حواله بانکی'), ('card', 'کارتخوان')], default='cash', max_length=20, verbose_name='روش پرداخت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expenseitem', verbose_name='آیتم')),
            ],
            options={
                'verbose_name': 'سابقه هزینه',
                'verbose_name_plural': 'سوابق هزینه\u200cها',
                'ordering': ['-date'],
            },
        ),
    ]
