# Generated by Django 5.1.7 on 2026-02-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='payment_method',
        ),
    ]
