# Generated by Django 5.1.7 on 2026-02-16 06:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
