# Generated by Django 5.1.7 on 2025-11-26 21:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Department Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-hire_date'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeeexpense',
            options={'ordering': ['-date'], 'verbose_name': 'Employee Expense', 'verbose_name_plural': 'Employee Expenses'},
        ),
        migrations.AlterModelOptions(
            name='salarypayment',
            options={'ordering': ['-date'], 'verbose_name': 'Salary Payment', 'verbose_name_plural': 'Salary Payments'},
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance')], default='full_time', max_length=20, verbose_name='Employment Type'),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Termination Date'),
        ),
        migrations.AddField(
            model_name='employeeexpense',
            name='category',
            field=models.CharField(choices=[('travel', 'Travel'), ('equipment', 'Equipment'), ('training', 'Training'), ('bonus', 'Bonus'), ('overtime', 'Overtime'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('digital', 'Digital Payment')], default='bank_transfer', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='debt_to_company',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Debt to Company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile', verbose_name='Employee Profile'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hire Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salary Due'),
        ),
        migrations.AlterField(
            model_name='employeeexpense',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='employeeexpense',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='employeeexpense',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='employeeexpense',
            name='expense',
            field=models.CharField(max_length=100, verbose_name='Expense Description'),
        ),
        migrations.AlterField(
            model_name='employeeexpense',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='employeeexpense',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='salary_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salary Amount'),
        ),
        migrations.AddIndex(
            model_name='employeeexpense',
            index=models.Index(fields=['date'], name='employee_em_date_aacf66_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeexpense',
            index=models.Index(fields=['category'], name='employee_em_categor_feaa2c_idx'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['date'], name='employee_sa_date_ab3fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['is_paid'], name='employee_sa_is_paid_74b1ab_idx'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.department', verbose_name='Department'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='employee_em_is_acti_b35377_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hire_date'], name='employee_em_hire_da_332649_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='employee_em_departm_e1e10e_idx'),
        ),
    ]
