# Generated by Django 5.1.7 on 2025-10-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_name_employee_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='national_id',
        ),
    ]
