# Generated by Django 5.1.7 on 2025-11-18 16:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Unique registered name of the company', max_length=255, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30, validators=[django.core.validators.RegexValidator('^[\\d\\+\\-\\s\\(\\)]+$', 'Invalid phone number format')])),
                ('email', models.EmailField(blank=True, max_length=255, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')])),
                ('address', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='accounts_co_name_a6c199_idx'), models.Index(fields=['phone'], name='accounts_co_phone_1b4cc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account', models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('saraf', 'saraf'), ('company', 'Company')], db_index=True, default='customer', help_text='Defines the user role and permissions in the system', max_length=20, verbose_name='Account Type')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('saraf', 'saraf'), ('company', 'Company')], db_index=True, default='customer', max_length=20, verbose_name='Role')),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30, validators=[django.core.validators.RegexValidator('^[\\d\\+\\-\\s\\(\\)]+$', 'Invalid phone number format')])),
                ('address', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='accounts.company', verbose_name='Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account'], name='accounts_us_account_c75fbb_idx'), models.Index(fields=['email'], name='accounts_us_email_4b84c1_idx'), models.Index(fields=['phone'], name='accounts_us_phone_27e73a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_user_profile')],
            },
        ),
    ]
