# Generated by Django 5.1.7 on 2025-11-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='accounts_us_account_c75fbb_idx',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account',
            field=models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('saraf', 'Saraf'), ('company', 'Company')], db_index=True, default='customer', help_text='Defines the user role and permissions in the system', max_length=20, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('saraf', 'Saraf'), ('company', 'Company')], db_index=True, default='customer', max_length=20, verbose_name='Role'),
        ),
    ]
