# Generated by Django 5.1.7 on 2026-01-19 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='product name')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='price')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='upload/product')),
                ('star', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('is_sale', models.BooleanField(default=False, verbose_name='discount')),
                ('sale_price', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='sale price')),
            ],
            options={
                'verbose_name': 'product',
            },
        ),
    ]
