# Generated by Django 5.1.7 on 2026-01-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='star',
        ),
    ]
