# Generated by Django 5.1.7 on 2026-02-07 12:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        ('containers', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('net_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('transactions_count', models.PositiveIntegerField(default=0)),
                ('items_sold', models.PositiveIntegerField(default=0)),
                ('customers_count', models.PositiveIntegerField(default=0)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('total_returns', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('total_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('avg_transaction_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('paid_transactions', models.PositiveIntegerField(default=0)),
                ('partial_transactions', models.PositiveIntegerField(default=0)),
                ('unpaid_transactions', models.PositiveIntegerField(default=0)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('payment_method_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('payment_method_card', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('payment_method_bank', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_final', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'خلاصه روزانه',
                'verbose_name_plural': 'خلاصه\u200cهای روزانه',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailySaleTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase')], default='sale', max_length=16)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('advance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_transactions', to='accounts.company')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_transactions', to='containers.container')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_transactions', to='accounts.userprofile')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_transactions', to='containers.inventory_list')),
            ],
            options={
                'verbose_name': 'Daily Sale Transaction',
                'verbose_name_plural': 'Daily Sale Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySaleTransactionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='containers.container')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_sale_items', to='containers.inventory_list')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='daily_sale.dailysaletransaction')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OutstandingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('transactions_count', models.PositiveIntegerField(default=0)),
                ('last_transaction', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outstanding', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-total_debt'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='daily_sale.dailysaletransaction')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dailysaletransaction',
            index=models.Index(fields=['date'], name='daily_sale__date_d8eecc_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysaletransaction',
            index=models.Index(fields=['transaction_type'], name='daily_sale__transac_b6cd94_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysaletransaction',
            index=models.Index(fields=['customer'], name='daily_sale__custome_60f04c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysaletransactionitem',
            unique_together={('transaction', 'item')},
        ),
    ]
