# Generated by Django 5.1.7 on 2025-11-19 21:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('containers', '0001_initial'),
        ('daily_sale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='old_transaction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='old_transaction',
            name='container',
        ),
        migrations.RemoveField(
            model_name='old_transaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='old_transaction',
            name='item',
        ),
        migrations.AlterModelOptions(
            name='dailysaletransaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'تراکنش هوشمند', 'verbose_name_plural': 'تراکنش\u200cهای هوشمند'},
        ),
        migrations.AlterModelOptions(
            name='dailysummary',
            options={'ordering': ['-date'], 'verbose_name': 'خلاصه هوشمند روزانه', 'verbose_name_plural': 'خلاصه\u200cهای هوشمند روزانه'},
        ),
        migrations.RemoveIndex(
            model_name='dailysaletransaction',
            name='daily_sale__custome_60f04c_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailysaletransaction',
            name='daily_sale__created_d5d1ac_idx',
        ),
        migrations.RemoveField(
            model_name='dailysaletransaction',
            name='day',
        ),
        migrations.RemoveField(
            model_name='dailysummary',
            name='total_expense',
        ),
        migrations.RemoveField(
            model_name='dailysummary',
            name='total_purchase',
        ),
        migrations.AddField(
            model_name='dailysaletransaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='مانده'),
        ),
        migrations.AddField(
            model_name='dailysaletransaction',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='جمع جزء'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='aed_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مجموع درهم'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='customers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد مشتریان'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='eur_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مجموع یورو'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='نهایی شده'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='items_sold',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد کالاهای فروخته شده'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='کل هزینه\u200cها'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='total_purchases',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='کل خرید'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='transactions_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد تراکنش\u200cها'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='usd_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مجموع دلار'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='پیش پرداخت'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='containers.container', verbose_name='کانتینر'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='currency',
            field=models.CharField(choices=[('usd', 'دلار'), ('eur', 'یورو'), ('aed', 'درهم')], default='usd', max_length=10, verbose_name='ارز'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='شماره فاکتور'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='containers.inventory_list', verbose_name='کالا'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='note',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مالیات'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'فروش'), ('purchase', 'خرید'), ('return', 'مرجوعی')], default='sale', max_length=20, verbose_name='نوع تراکنش'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='date',
            field=models.DateField(db_index=True, unique=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='net_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مانده خالص'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='note',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='کل سود'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='کل فروش'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AddIndex(
            model_name='dailysaletransaction',
            index=models.Index(fields=['status'], name='daily_sale__status_039d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysaletransaction',
            index=models.Index(fields=['invoice_number'], name='daily_sale__invoice_424224_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['is_final'], name='daily_sale__is_fina_a1cca4_idx'),
        ),
        migrations.DeleteModel(
            name='Old_Transaction',
        ),
    ]
