# Generated by Django 5.1.7 on 2025-12-16 12:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
