# Generated by Django 5.1.7 on 2026-01-07 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('daily_sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysaletransactionitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company'),
        ),
    ]
