# Generated by Django 5.1.7 on 2025-10-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sale', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyExpense',
        ),
    ]
