# Generated by Django 5.1.7 on 2025-11-20 12:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('containers', '0001_initial'),
        ('daily_sale', '0002_remove_old_transaction_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysaletransaction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Advance'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='containers.container', verbose_name='Container'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created_by'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('eur', 'eur'), ('aed', 'aed')], default='usd', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Discription'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Invoice Nubber'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='containers.inventory_list', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('cancelled', 'cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'purchase')], default='sale', max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='customers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Customer Quantity'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='date',
            field=models.DateField(db_index=True, unique=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='items_sold',
            field=models.PositiveIntegerField(default=0, verbose_name='Items Sold'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='net_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Net Balance'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total Expenses'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total Profit'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_purchases',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total Purcheses'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total Sales'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='transactions_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Transaction Quantity'),
        ),
    ]
