# Generated by Django 5.1.7 on 2025-12-16 12:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sale', '0002_alter_dailysaletransaction_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysaletransaction',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
