# Generated by Django 5.1.7 on 2025-11-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sale', '0003_alter_dailysaletransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysummary',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='dailysummary',
            name='eur_total',
        ),
        migrations.RemoveField(
            model_name='dailysummary',
            name='usd_total',
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='currency',
            field=models.CharField(choices=[('aed', 'aed')], default='usd', max_length=10, verbose_name='Currency'),
        ),
    ]
