# Generated by Django 5.1.7 on 2025-11-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sale', '0004_alter_dailysummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='eur_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total EUR'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='usd_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total USD'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('eur', 'eur'), ('aed', 'aed')], default='usd', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='aed_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total AED'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='Is final'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
