# Generated by Django 5.1.7 on 2025-11-18 15:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('containers', '__first__'),
        ('daily_sale', '0004_dailyexpense_dailysalerecord_oldtransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySaleTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('day', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('return', 'Return')], default='sale', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('advance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('aed', 'AED')], default='usd', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='containers.container')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='containers.inventory_list')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_purchase', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Old_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('day', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyExpense',
        ),
        migrations.DeleteModel(
            name='DailySaleRecord',
        ),
        migrations.DeleteModel(
            name='OldTransaction',
        ),
        migrations.DeleteModel(
            name='SaleInvoice',
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['date'], name='daily_sale__date_6ec052_idx'),
        ),
        migrations.AddField(
            model_name='old_transaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company'),
        ),
        migrations.AddField(
            model_name='old_transaction',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='containers.container'),
        ),
        migrations.AddField(
            model_name='old_transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='old_transaction',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='containers.inventory_list'),
        ),
        migrations.AddIndex(
            model_name='dailysaletransaction',
            index=models.Index(fields=['date'], name='daily_sale__date_d8eecc_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysaletransaction',
            index=models.Index(fields=['transaction_type'], name='daily_sale__transac_b6cd94_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysaletransaction',
            index=models.Index(fields=['customer'], name='daily_sale__custome_60f04c_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysaletransaction',
            index=models.Index(fields=['created_at'], name='daily_sale__created_d5d1ac_idx'),
        ),
    ]
