# Generated by Django 5.1.7 on 2025-11-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sale', '0005_dailysummary_eur_total_dailysummary_usd_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='advance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Advance'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='tax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='aed_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Total AED'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='eur_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Total EUR'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='net_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Net Balance'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_expenses',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Total Expenses'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_profit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Total Profit'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_purchases',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Total Purcheses'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Total Sales'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='usd_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Total USD'),
        ),
    ]
