# Generated by Django 5.1.7 on 2025-11-24 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sale', '0006_alter_dailysaletransaction_advance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('aed', 'AED')], default='usd', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase')], default='sale', max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='customers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Customers Count'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='Is Final'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_purchases',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Total Purchases'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='transactions_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Transactions Count'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
