# Generated by Django 5.1.7 on 2025-11-26 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sale', '0007_alter_dailysaletransaction_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysaletransaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Daily Sale Transaction', 'verbose_name_plural': 'Daily Sale Transactions'},
        ),
        migrations.AlterModelOptions(
            name='dailysummary',
            options={'ordering': ['-date'], 'verbose_name': 'Daily Summary', 'verbose_name_plural': 'Daily Summaries'},
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='advance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Advance Payment'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
    ]
