# Generated by Django 5.1.7 on 2025-11-30 12:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('daily_sale', '0008_alter_dailysaletransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Advance Payment'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='aed_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24, verbose_name='Total AED'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='eur_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24, verbose_name='Total EUR'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='net_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24, verbose_name='Net Balance'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24, verbose_name='Total Expenses'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24, verbose_name='Total Profit'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_purchases',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24, verbose_name='Total Purchases'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24, verbose_name='Total Sales'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='usd_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24, verbose_name='Total USD'),
        ),
        migrations.CreateModel(
            name='OldTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_debt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24)),
                ('transactions_count', models.PositiveIntegerField(default=0)),
                ('last_transaction', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='old_transaction', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Outstanding Customer',
                'verbose_name_plural': 'Outstanding Customers',
                'ordering': ['-total_debt', 'customer'],
            },
        ),
    ]
