# Generated by Django 5.1.7 on 2025-12-01 10:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('containers', '0005_remove_saraftransaction_debit_company'),
        ('daily_sale', '0009_alter_dailysaletransaction_advance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySummary',
        ),
        migrations.RemoveField(
            model_name='oldtransaction',
            name='customer',
        ),
        migrations.RemoveIndex(
            model_name='dailysaletransaction',
            name='daily_sale__invoice_424224_idx',
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_transactions_for_company', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_transactions_for_container', to='containers.container'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('aed', 'AED')], default='usd', max_length=8),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_transactions_for_customer', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_transactions_for_item', to='containers.inventory_list'),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase')], default='sale', max_length=16),
        ),
        migrations.AlterField(
            model_name='dailysaletransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddIndex(
            model_name='dailysaletransaction',
            index=models.Index(fields=['customer'], name='daily_sale__custome_60f04c_idx'),
        ),
        migrations.DeleteModel(
            name='OldTransaction',
        ),
    ]
